dist: bionic
os: linux

language: rust
cache: cargo

jobs:
  fast_finish: true

  include:
    - name: "Stable"
      rust: stable
      script: 
        - cargo build --verbose --all
        - cargo test --verbose --all

    - name: "Beta"
      rust: beta
        - cargo build --verbose --all
        - cargo test --verbose --all

    - name: "Nightly"
      rust: nightly
      script: 
        - cargo build --verbose --all
        - cargo test --verbose --all

  allow_failures:
    - rust: nightly
