dist: bionic
os: linux

language: rust
cache: cargo

jobs:
  fast_finish: true

  include:
    - name: "Stable"
      if: type != pull_request
      rust: stable
    - name: "Beta"
      if: type != pull_request
      rust: beta
    - name: "Nightly"
      if: type != pull_request
      rust: nightly

    - name: "Squashed commits"
      if: type = pull_request
      env: BRANCH="origin/$TRAVIS_PULL_REQUEST_BRANCH"
      script: 
        - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        - git fetch origin
        - scripts/squashed

  allow_failures:
    - rust: nightly
      
script:
  - cargo build --verbose --all
  - scripts/check test
  - rustup component add clippy || cargo install --git
    https://github.com/rust-lang/rust-clippy/ --force clippy
  - rustup component add rustfmt
  - scripts/check lintformat

after_success:
  - cargo doc --document-private-items --no-deps

deploy:
  - provider: pages
    local_dir: target/doc
    fqdn: slide-dev.ayazhafiz.com
    project_name: slide
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    committer_from_gh: true
    deployment_file: true
    target_branch: gh-pages
    on:
      branch: master
